document.getElementById("Home").innerHTML = "Home";
document.getElementById("Gallery") .innerHTML = "Gallery";
document.getElementById("Models") .innerHTML = "Models";
document.getElementById("About") .innerHTML = "About";
document.getElementById("Contact") .innerHTML = "Contact";
document.getElementById("button-1") .innerHTML = "Login";
document.getElementById("hero-text") .innerHTML = "Mercedes";
document.getElementById("gallery-title") .innerHTML = "Gallery"
document.getElementById("title-1") .innerHTML = "The Mercedes Gallery"
document.getElementById("button-2") .innerHTML = "Explore More";
document.getElementById("models-title") .innerHTML = "Models";
document.getElementById("button-3") .innerHTML = "Electric";
document.getElementById("button-4") .innerHTML = "Luxury";
document.getElementById("tiguan") .innerHTML = "Volkswagen Tiguan";
document.getElementById("bmw") .innerHTML = "BMW 8";
document.getElementById("mini") .innerHTML = "Mini Cooper";
document.getElementById("fe") .innerHTML = "Ferrari F8";
document.getElementById("ma") .innerHTML = "Maserati GranCabrio";
document.getElementById("audi") .innerHTML = "Audi SQ8";
document.getElementById("mer") .innerHTML = "Mercedes-Benz";
document.getElementById("po") .innerHTML = "Porsche";